### ISSUE TITLE
Upgrading to Tokio v1

### ISSUE THREAD

**Issue by billyb2** [mandreyel/cratetorrent#101]
I've recently been working on cratetorrent, and it's really great. The only gripe I have is that it uses Tokio v0.2, instead of Tokio v1, making it incompatible with a project I'm working on.

**Comment by mandreyel** [comment]
Very glad that you like using the crate so far, @billyb2!

Yes, cratetorrent had been released just before Tokio v1 and I haven't had the chance to work on it ever since (hence the slow reply, apologies for that). I will make this as one of my first tasks when I get the chance to work on this again, which should be in the next couple of weeks.
